// v4.30.0 — artifact generation (council round 61, Claude seat's revised spec).
// artBuild is LIFTED AND RUN. The invariant — no prose is generated, every body
// byte is a seat's verbatim text — cannot be shown by inspecting shapes.
const fs=require("fs"),src=fs.readFileSync("app.js","utf8");
const grab=(re)=>{const m=src.match(re);if(!m)throw new Error("lift failed "+re);return m[0];};
const LOGS=[];
globalThis.logError=(m)=>LOGS.push(String(m));
eval([grab(/  const clip = .*/),
      grab(/  function artifactsEnabled\(\) \{.*\}/),
      grab(/  function artTag\(e\) \{[\s\S]*?\n  \}/),
      grab(/  function artProvenance\(e, tag, seats\) \{[\s\S]*?\n  \}/),
      grab(/  const ART_MEANING = \{[\s\S]*?\n  \};/).replace(/^\s*const /,"var "),
      grab(/  function artHeader\(e, tag, title\) \{[\s\S]*?\n  \}/),
      grab(/  function artSignature\(e, seats\) \{[\s\S]*?\n  \}/),
      grab(/  function artBuild\(e\) \{[\s\S]*?\n  \}/)].join("\n") +
     "\nglobalThis.artBuild=artBuild;globalThis.artTag=artTag;");

let p=0,f=0;
const t=(n,g,w)=>{const ok=JSON.stringify(g)===JSON.stringify(w);ok?(p++,console.log("  PASS  "+n)):(f++,console.log("  FAIL  "+n+"  got "+JSON.stringify(g)));};
const tt=(n,c)=>t(n,!!c,true);
const R=(o,extra)=>Object.assign({t:Date.now(),prompt:"Should the floor stay at 0.600?",outcome:o,counts:"3/3",
  positions:[{seat:"gemini",text:"GEMINI_TEXT_ALPHA"},{seat:"kimi",text:"KIMI_TEXT_BETA"},{seat:"claude",text:"CLAUDE_TEXT_GAMMA"}]},extra||{});

console.log("\n--- the verdict mapping, exactly as specified ---");
t("VERIFIED -> one file", artBuild(R("verified",{verdict:"SPOKEN_TEXT"})).length, 1);
t("PROVISIONAL -> one file", artBuild(R("provisional",{verdict:"X"})).length, 1);
t("SOLE -> one file", artBuild(R("sole",{verdict:"X"})).length, 1);
t("DIVIDED-PARALLEL -> one file PER SEAT",
  artBuild(R("divided",{cs:{verdict:"PARALLEL"}})).length, 3);
t("DIVIDED not parallel -> ONE file, labelled sections",
  artBuild(R("divided",{cs:{verdict:"TRUE SPLIT"}})).length, 1);

console.log("\n--- THE INVARIANT: no prose is generated ---");
const v=artBuild(R("verified",{verdict:"SPOKEN_TEXT"}))[0].body;
tt("the VERIFIED body is the speaking seat's text verbatim", v.includes("SPOKEN_TEXT"));
tt("the signature block LISTS seats, it does not summarise them",
   /CONFIRMING SEATS/.test(v) && /- gemini/.test(v) && /- kimi/.test(v));
tt("and says so explicitly",
   /No text above it was generated by this tool/.test(v));
const d=artBuild(R("divided",{cs:{verdict:"TRUE SPLIT"}}))[0].body;
tt("a DIVIDED file contains every position verbatim",
   d.includes("GEMINI_TEXT_ALPHA") && d.includes("KIMI_TEXT_BETA") && d.includes("CLAUDE_TEXT_GAMMA"));
tt("with NO connecting prose between them",
   /no connecting prose has been written/i.test(d) && /no resolution is implied/i.test(d));

console.log("\n--- parallel files are never merged ---");
const par=artBuild(R("divided",{cs:{verdict:"PARALLEL"}}));
tt("each file holds exactly ONE seat's text",
   par[0].body.includes("GEMINI_TEXT_ALPHA") && !par[0].body.includes("KIMI_TEXT_BETA"));
tt("and each carries the full warning, since one may be forwarded alone",
   par.every(x=>/DIVIDED-PARALLEL/.test(x.body) && /does not represent the council/.test(x.body)));

console.log("\n--- Kimi's controlling constraint: the tag rides everywhere ---");
["verified","provisional","sole"].forEach(o=>{
  const files=artBuild(R(o,{verdict:"X"}));
  tt(o+": tag in the FILENAME", /^\[[A-Z-]+\]/.test(files[0].name));
  tt(o+": tag in the FIRST LINE", /^---[\s\S]*?\n\[[A-Z-]+\]/.test(files[0].body) || /\[[A-Z-]+\]/.test(files[0].body.split("\n").find(l=>l.startsWith("["))||""));
});
tt("and each tag carries a plain-language meaning for a reader who has never seen this system",
   /NOT authoritative advice/.test(artBuild(R("verified",{verdict:"X"}))[0].body) &&
   /ONE SEAT ONLY/.test(artBuild(R("sole",{verdict:"X"}))[0].body));

console.log("\n--- provenance travels INSIDE the file (Gemini's frontmatter) ---");
tt("YAML frontmatter is present", /^---\ngenerator: Red Queen/.test(v));
tt("the sign-off notice is embedded",
   /UNAUDITED MULTI-MODEL DRAFT — REQUIRES OPERATOR SIGN-OFF BEFORE USE/.test(v));
const px=artBuild(R("verified",{verdict:"X",counterfoils:[{declared_seat:"kimi",proxy:true,actual_model:"minimax-m2.7"}]}))[0].body;
tt("a proxy seat is disclosed in the frontmatter AND the signature",
   /proxy_warning/.test(px) && /NOT the seat itself/.test(px));
tt("empty retrieval is disclosed",
   /seats worked from recent rounds only/.test(artBuild(R("verified",{verdict:"X",retrieval_hit:false}))[0].body));
tt("partial agreement is stated rather than implied",
   /2 of 3 seats agreed/.test(artBuild(R("verified",{verdict:"X",counts:"2/3"}))[0].body));

console.log("\n--- shape ---");
tt("no merge step, no summariser, no generative call in the export path",
   !/artBuild[\s\S]{0,3000}(?:fetch\(|callGemini|callKimi|callClaude)/.test(src));
tt("the council's own gap-closing quote is in source",
   /already agreed on/.test(src) && /unelected fourth seat/.test(src));
tt("Gemini's inert-Blob constraint is implemented",
   /URL\.createObjectURL/.test(src) && /a\.click\(\)/.test(src));
tt("docx is real OOXML, not a renamed text file",
   /word\/document\.xml/.test(src) && /\[Content_Types\]\.xml/.test(src));
tt("flag defaults OFF", /localStorage\.getItem\("rq_artifacts"\) === "on"/.test(src));

console.log("\n--- v4.30.1: reachable on a phone, and no lag ---");
tt("an export panel is rendered, not console-only",
   /function artPanel\(e\)/.test(src) && /artPanel\(_rows\[_rows\.length - 1\]\)/.test(src));
tt("it appears AFTER the answer renders",
   src.indexOf("stageEnd();\n    // v4.30.1") < src.indexOf("if (divided) {"));
tt("the ledger row exists before the panel reads it \u2014 zero lag",
   src.indexOf("recordLedger({") < src.indexOf("artPanel(_rows["));
tt("the label states the FILE COUNT, because 3 files means 3 unreconciled positions",
   /files\.length \+ " files, one per seat/.test(src));
tt("all three formats are offered", /\["Markdown", "md"\], \["Word", "docx"\], \["Text", "txt"\]/.test(src));
tt("the panel clears when a new round starts", /artPanelClose\(\); \} catch \(_\) \{\}/.test(src));
tt("the console entry points still work", /window\.__rqExport = artExport/.test(src));

console.log("\n"+p+" passed, "+f+" failed");
process.exit(f?1:0);
